version: "3.9"

# ---------------------------------------------------
# Global environment variables (tweak here)
# These will be injected into all services via the x-env-defaults anchor
# ---------------------------------------------------
x-env-defaults: &env-defaults 
  # MinIO
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  # PostgreSQL + pgvector
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  # Redis
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  # Qdrant API key for authentication
  QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}

services:
  # ---------- Storage & Data Layers ----------
  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=my-bucket
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      <<: *env-defaults
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    environment:
      <<: *env-defaults
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  n8n:
    image: n8nio/n8n:latest
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - postgres

# ---------- Volumes ----------
volumes:
  minio-data:
  postgres-data:
  qdrant-data:
  redis-data:
  n8n-data:
