version: "3.9"

# ---------------------------------------------------
# Global environment variables (tweak here)
# These will be injected into all services via the x-env-defaults anchor
# ---------------------------------------------------
x-env-defaults: &env-defaults 
  # MinIO
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  # PostgreSQL + pgvector
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  # Redis
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  # Qdrant API key for authentication
  QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}

services:
  # ---------- Storage & Data Layers ----------
  minio:
    image: minio/minio:latest
    environment:
      <<: *env-defaults
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      <<: *env-defaults
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    environment:
      <<: *env-defaults
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  # ---------- Agent / Orchestration Frameworks ----------
  superagi:
    image: superagidev/superagi:main
    environment:
      <<: *env-defaults
      # SuperAGI uses DATABASE_URL + Redis + MinIO + Qdrant
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      QDRANT_URL: "http://qdrant:6333"
    ports:
      - "8000:8000"

  haystack:
    image: deepset/haystack:base-v2.15.1
    environment:
      <<: *env-defaults
      # Haystack config
      DB_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: "6333"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "8001:8001"


# ---------- Volumes ----------
volumes:
  minio-data:
  postgres-data:
  qdrant-data:
  redis-data:
